"""
generator.py — Shared dataset generation module.

Reuses value resolvers from cli/defaults.py and provides in-memory
formatters so the Flask API can return file content without writing to disk.
"""

import csv
import io
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from defaults import resolve_default

SUPPORTED_TYPES = {
    "json":  {"ext": ".json",  "mime": "application/json"},
    "jsonl": {"ext": ".jsonl", "mime": "application/x-ndjson"},
    "csv":   {"ext": ".csv",   "mime": "text/csv"},
    "tsv":   {"ext": ".tsv",   "mime": "text/tab-separated-values"},
    "sql":   {"ext": ".sql",   "mime": "application/sql"},
    "xml":   {"ext": ".xml",   "mime": "application/xml"},
    "yaml":  {"ext": ".yaml",  "mime": "text/yaml"},
}

DEFAULT_SOURCES = [
    {"name": "default-nums-asc",   "description": "Ascending numbers 1…N"},
    {"name": "default-nums-desc",  "description": "Descending numbers N…1"},
    {"name": "default-nums-rand",  "description": "Random integers in [1, N]"},
    {"name": "default-az",         "description": "a, b, …, z (cycled)"},
    {"name": "default-za",         "description": "z, y, …, a (cycled)"},
    {"name": "default-AZ",         "description": "A, B, …, Z (cycled)"},
    {"name": "default-ZA",         "description": "Z, Y, …, A (cycled)"},
    {"name": "default-aZ",         "description": "a-z then A-Z (cycled)"},
    {"name": "default-Az",         "description": "A-Z then a-z (cycled)"},
    {"name": "default-zA",         "description": "z-a then Z-A (cycled)"},
    {"name": "default-Za",         "description": "Z-A then z-a (cycled)"},
    {"name": "default-az-rand",    "description": "Random lowercase letter"},
    {"name": "default-AZ-rand",    "description": "Random uppercase letter"},
    {"name": "default-Az-rand",    "description": "Random letter (mixed case)"},
    {"name": "default-access-log", "description": "Random access-log entries generated by flog"},
]


def resolve_values(value_source: str, row_count: int) -> list[str]:
    if value_source.startswith("default-"):
        return resolve_default(value_source, row_count)
    raise ValueError(f"Unknown value source: '{value_source}'. Use /api/defaults to see available sources.")


def resolve_file_values(file_text: str, row_count: int, cycle: bool = False, randomize: bool = False) -> list[str]:
    """
    Resolve values from uploaded file content (one value per line).

    Flags (combinable):
        cycle     — repeat file lines cyclically to fill row_count
        randomize — shuffle / randomly pick values
        both      — cycle to fill, then shuffle the result
    """
    import itertools
    import random

    lines = [line.rstrip("\n\r") for line in file_text.splitlines()]
    if not lines:
        return [""] * row_count

    if cycle and randomize:
        # Cycle to fill, then shuffle
        result = list(itertools.islice(itertools.cycle(lines), row_count))
        random.shuffle(result)
        return result
    elif cycle:
        return list(itertools.islice(itertools.cycle(lines), row_count))
    elif randomize:
        # Shuffle file lines but do NOT repeat beyond the file length
        shuffled = lines[:]
        random.shuffle(shuffled)
        if len(shuffled) < row_count:
            shuffled.extend([""] * (row_count - len(shuffled)))
        return shuffled[:row_count]
    else:
        # normal — pad with empty strings
        if len(lines) < row_count:
            lines.extend([""] * (row_count - len(lines)))
        return lines[:row_count]


def resolve_custom_values(rules: list[dict], row_count: int) -> list[str]:
    """
    Resolve values from user-defined range rules.

    Each rule is a dict: {"from": int, "to": int, "value": str}
    Rows are 1-indexed.  Unspecified rows default to "".
    Later rules overwrite earlier ones on overlap.
    """
    result = [""] * row_count
    for rule in rules:
        start = max(1, int(rule.get("from", 1))) - 1        # convert to 0-indexed
        end = min(row_count, int(rule.get("to", row_count)))  # inclusive, 1-indexed
        value = str(rule.get("value", ""))
        for i in range(start, end):
            result[i] = value
    return result


def _format_json(rows: list[dict], **_kw) -> str:
    return json.dumps(rows, ensure_ascii=False, indent=2)


def _format_jsonl(rows: list[dict], **_kw) -> str:
    return "\n".join(json.dumps(r, ensure_ascii=False) for r in rows) + "\n"


def _format_csv(rows: list[dict], **_kw) -> str:
    if not rows:
        return ""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def _format_tsv(rows: list[dict], **_kw) -> str:
    if not rows:
        return ""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()), delimiter="\t")
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()


def _sql_escape(value: str) -> str:
    return value.replace("'", "''")


def _format_sql(rows: list[dict], table_name: str = "data", **_kw) -> str:
    if not rows:
        return f"CREATE TABLE {table_name} ();\n"
    keys = list(rows[0].keys())
    lines = []
    col_defs = ", ".join(f"{k} TEXT" for k in keys)
    lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} ({col_defs});")
    lines.append("")
    for row in rows:
        vals = ", ".join(f"'{_sql_escape(str(row[k]))}'" for k in keys)
        lines.append(f"INSERT INTO {table_name} ({', '.join(keys)}) VALUES ({vals});")
    return "\n".join(lines) + "\n"


def _format_xml(rows: list[dict], table_name: str = "data", **_kw) -> str:
    from xml.sax.saxutils import escape as xml_escape
    lines = []
    lines.append('<?xml version="1.0" encoding="UTF-8"?>')
    lines.append(f"<{table_name}>")
    for row in rows:
        lines.append("  <row>")
        for k, v in row.items():
            lines.append(f"    <{k}>{xml_escape(str(v))}</{k}>")
        lines.append("  </row>")
    lines.append(f"</{table_name}>")
    return "\n".join(lines) + "\n"


def _format_yaml(rows: list[dict], **_kw) -> str:
    lines = []
    for row in rows:
        first = True
        for k, v in row.items():
            prefix = "- " if first else "  "
            val = str(v)
            needs_quote = any(c in val for c in (":", "#", "'", '"', "\n", "[", "]", "{", "}")) or val == ""
            formatted = f'"{val}"' if needs_quote else val
            lines.append(f"{prefix}{k}: {formatted}")
            first = False
    return "\n".join(lines) + "\n"


_FORMATTERS = {
    "json":  _format_json,
    "jsonl": _format_jsonl,
    "csv":   _format_csv,
    "tsv":   _format_tsv,
    "sql":   _format_sql,
    "xml":   _format_xml,
    "yaml":  _format_yaml,
}


def generate_dataset(
    rows: int,
    keys: list[str],
    values: list[str],
    fmt: str = "json",
    table_name: str = "data",
    file_overrides: dict[int, list[str]] | None = None,
) -> tuple[str, str, str]:
    """
    Generate a dataset and return (content, filename, mime_type).

    Parameters
    ----------
    rows           : number of rows
    keys           : list of column names
    values         : list of value sources (one per key)
    fmt            : output format (json, csv, tsv, sql, xml, yaml, jsonl)
    table_name     : table/root name for SQL/XML output
    file_overrides : dict mapping column index → pre-resolved list[str] from uploaded files

    Returns
    -------
    (content_str, filename, mime_type)
    """
    if file_overrides is None:
        file_overrides = {}

    if fmt not in SUPPORTED_TYPES:
        raise ValueError(f"Unsupported format '{fmt}'. Choose from: {', '.join(SUPPORTED_TYPES.keys())}")

    if len(keys) != len(values):
        raise ValueError(
            f"Number of keys ({len(keys)}) does not match number of values ({len(values)})."
        )

    if rows <= 0:
        raise ValueError("Row count must be a positive integer.")
    if rows > 100000:
        raise ValueError("Row count must be less than or equal to 100000.")

    columns: dict[str, list[str]] = {}
    for i, (key, val_src) in enumerate(zip(keys, values)):
        if i in file_overrides:
            columns[key] = file_overrides[i]
        else:
            columns[key] = resolve_values(val_src, rows)

    row_dicts: list[dict] = []
    for i in range(rows):
        row = {}
        for key in keys:
            col = columns[key]
            row[key] = col[i] if i < len(col) else ""
        row_dicts.append(row)

    formatter = _FORMATTERS[fmt]
    content = formatter(row_dicts, table_name=table_name)

    type_info = SUPPORTED_TYPES[fmt]
    filename = f"dataset{type_info['ext']}"
    mime_type = type_info["mime"]

    return content, filename, mime_type

